<?php

namespace MyRRD;

const ARCHIVE_TYPE_INT = 0;
const ARCHIVE_TYPE_INT32 = ARCHIVE_TYPE_INT;
const ARCHIVE_TYPE_INT64 = 1;
const ARCHIVE_TYPE_FLOAT = 2;
const ARCHIVE_TYPE_BOOL = 8;
const ARCHIVE_TYPE_BOOLEAN = ARCHIVE_TYPE_BOOL;

const ARCHIVE_AGGREGATION_FUNCTION_AVG = 0;
const ARCHIVE_AGGREGATION_FUNCTION_MIN = 1;
const ARCHIVE_AGGREGATION_FUNCTION_MAX = 2;
const ARCHIVE_AGGREGATION_FUNCTION_FIRST = 3;
const ARCHIVE_AGGREGATION_FUNCTION_LAST = 4;
